# ansible-playbook install_car.yml -v
---
- hosts: cars
  become: yes
  become_method: sudo

  vars:
    app_path: /opt/car_server
    app_user: car
    git_path: https://github.com/telminov/arduino-battle-server.git
    tmp_checkout_path: /tmp/github_project

  tasks:
    - name: update apt cache
      apt: update_cache=yes

    - name: install packages
      apt: name={{ item }}
      with_items:
        - git

    - name: install virtual env
      pip: name=virtualenv

    - name: create car user
      user: name={{ app_user }}

    - name: clear app directory
      file: path={{ app_path }} state=absent

    - name: clear checkout directory
      file: path={{ tmp_checkout_path }} state=absent

    - name: create car app direcotry
      file: path={{ app_path }} state=directory mode=755 owner=car

    - name: checkout code
      git: repo={{ git_path }} dest={{ tmp_checkout_path }}

    - name: move car code
      shell: mv /tmp/github_project/car_server/* /opt/car_server/

    - name: initiate virtualenv
      pip: virtualenv="{{ app_path }}/virt_env"
           virtualenv_python=python3.4
           requirements={{ app_path }}/requirements.txt

    - name: set file woner
      file: path={{ app_path }} recurse=yes owner=car

    - name: remove tmp file
      file: path={{ item }}
      with_items:
        - "{{ tmp_checkout_path }}"